


CREATE DATABASE IF NOT EXISTS mce_db;
use mce_db;
DROP TABLE IF EXISTS ads;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
  id INT UNSIGNED NOT NULL  AUTO_INCREMENT,
  username VARCHAR(240) NOT NULL,
  email VARCHAR(200) NOT NULL,
  password VARCHAR(240) NOT NULL,
  PRIMARY KEY (id)
);


Create table categories(
id int UNSIGNED not null AUTO_INCREMENT,
  name VARCHAR(240) not null,
  PRIMARY KEY (id)
);

CREATE TABLE ads(
  id INT UNSIGNED NOT NULL  AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
  ON DELETE CASCADE
);
